"""add_user_sessions

Revision ID: 32f652f45431
Revises: 6566178cd69c
Create Date: 2026-07-27 14:18:44.954065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f652f45431'
down_revision: Union[str, Sequence[str], None] = '6566178cd69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A `user_sessions` table may already exist from the old Express app's
    # connect-pg-simple store (columns: sid/sess/expire) -- an incompatible
    # shape we're replacing outright. Session tables are disposable by
    # nature (dropping it just logs everyone out), so it's safe to drop any
    # pre-existing table with this name before creating the real one below.
    op.execute("DROP TABLE IF EXISTS user_sessions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index('user_sessions_expires_at_index', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('user_sessions_user_id_index', 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_sessions_user_id_index', table_name='user_sessions')
    op.drop_index('user_sessions_expires_at_index', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
