"""initial_schema

Revision ID: 6566178cd69c
Revises: 
Create Date: 2026-07-27 14:18:01.972037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6566178cd69c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(email)) > 0', name=op.f('users_email_not_empty')),
    sa.CheckConstraint('char_length(trim(name)) >= 2', name=op.f('users_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('users_email_unique', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(title)) > 0', name=op.f('topics_title_not_empty')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index('topics_user_id_index', 'topics', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('chat_messages_role_check')),
    sa.CheckConstraint('char_length(trim(message)) > 0', name=op.f('chat_messages_message_not_empty')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_chat_messages_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('chat_messages_topic_created_at_index', 'chat_messages', ['topic_id', 'created_at'], unique=False)
    op.create_index('chat_messages_topic_id_index', 'chat_messages', ['topic_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(content)) > 0', name=op.f('notes_content_not_empty')),
    sa.CheckConstraint('char_length(trim(title)) > 0', name=op.f('notes_title_not_empty')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_notes_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('notes_topic_id_index', 'notes', ['topic_id'], unique=False)
    op.create_table('study_activities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('topic_created','topic_updated','note_created','note_updated','note_moved','ai_chat')", name=op.f('study_activities_type_check')),
    sa.CheckConstraint('char_length(trim(description)) > 0', name=op.f('study_activities_description_not_empty')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_study_activities_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_activities'))
    )
    op.create_index('study_activities_topic_id_index', 'study_activities', ['topic_id'], unique=False)
    op.create_index('study_activities_user_created_at_index', 'study_activities', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('study_activities_user_created_at_index', table_name='study_activities')
    op.drop_index('study_activities_topic_id_index', table_name='study_activities')
    op.drop_table('study_activities')
    op.drop_index('notes_topic_id_index', table_name='notes')
    op.drop_table('notes')
    op.drop_index('chat_messages_topic_id_index', table_name='chat_messages')
    op.drop_index('chat_messages_topic_created_at_index', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('topics_user_id_index', table_name='topics')
    op.drop_table('topics')
    op.drop_index('users_email_unique', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
