"""add_rag_tables

Revision ID: a30c5cd8f9a6
Revises: 32f652f45431
Create Date: 2026-07-27 15:17:12.307721

Hand-written, not autogenerated: pgvector isn't installed on the local dev
Postgres yet (a prerequisite for even connecting to introspect a `vector`
column), so `alembic revision --autogenerate` can't run here. This mirrors
`app/modules/ai/model.py`'s `Document`, `DocumentChunk`, `MessageSource`
exactly -- re-run `alembic revision --autogenerate -m "check"` once pgvector
is available and confirm it produces an empty diff against this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a30c5cd8f9a6'
down_revision: Union[str, Sequence[str], None] = '32f652f45431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 768


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        'documents',
        sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('topic_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('content_type', sa.String(length=100), nullable=False),
        sa.Column('storage_path', sa.Text(), nullable=True),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed')",
            name=op.f('documents_status_check'),
        ),
        sa.CheckConstraint('char_length(trim(title)) > 0', name=op.f('documents_title_not_empty')),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_documents_topic_id_topics'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    )
    op.create_index('documents_topic_id_index', 'documents', ['topic_id'], unique=False)

    op.create_table(
        'document_chunks',
        sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('topic_id', sa.BigInteger(), nullable=False),
        sa.Column('note_id', sa.BigInteger(), nullable=True),
        sa.Column('document_id', sa.BigInteger(), nullable=True),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', Vector(EMBEDDING_DIM), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "(note_id IS NOT NULL AND document_id IS NULL) OR "
            "(note_id IS NULL AND document_id IS NOT NULL)",
            name=op.f('document_chunks_exactly_one_source'),
        ),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_document_chunks_topic_id_topics'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_document_chunks_note_id_notes'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    )
    op.create_index('document_chunks_topic_id_index', 'document_chunks', ['topic_id'], unique=False)
    op.create_index('document_chunks_note_id_index', 'document_chunks', ['note_id'], unique=False)
    op.create_index('document_chunks_document_id_index', 'document_chunks', ['document_id'], unique=False)
    op.create_index(
        'document_chunks_embedding_hnsw_index', 'document_chunks', ['embedding'],
        unique=False, postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )

    op.create_table(
        'message_sources',
        sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('message_id', sa.BigInteger(), nullable=False),
        sa.Column('chunk_id', sa.BigInteger(), nullable=True),
        sa.Column('similarity_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_message_sources_message_id_chat_messages'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_message_sources_chunk_id_document_chunks'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_message_sources')),
    )
    op.create_index('message_sources_message_id_index', 'message_sources', ['message_id'], unique=False)


def downgrade() -> None:
    op.drop_index('message_sources_message_id_index', table_name='message_sources')
    op.drop_table('message_sources')

    op.drop_index('document_chunks_embedding_hnsw_index', table_name='document_chunks')
    op.drop_index('document_chunks_document_id_index', table_name='document_chunks')
    op.drop_index('document_chunks_note_id_index', table_name='document_chunks')
    op.drop_index('document_chunks_topic_id_index', table_name='document_chunks')
    op.drop_table('document_chunks')

    op.drop_index('documents_topic_id_index', table_name='documents')
    op.drop_table('documents')
