'use client'

import { useEffect, useMemo, useState } from 'react'
import { api, messageFromError } from '../lib/api'
import { useNavigate } from '../lib/navigation'

type Overview={totalActivities:number;activitiesThisWeek:number;aiInteractions:number;topicsStudied:number;currentStreak:number;longestStreak:number;totalXp:number;overallLevelName:string;activityTrend:{date:string;count:number}[];mastery:{totalConcepts:number;averageMastery:number|null;weakCount:number;strongCount:number};weakestConcepts:{conceptId:number;conceptName:string;topicId:number;topicTitle:string;masteryScore:number}[];topics:{topicId:number;title:string;conceptCount:number;averageMastery:number|null;levelName:string;totalXp:number}[]}
type Activity={id:number;activity_type:string;created_at:string}
type Deck={topic_id:number;total:number;due_today:number;retention_rate:number|null}

const COLORS=['#6d5ef6','#e8845a','#5ab58e','#d5a928','#9b7ea5']
const ICONS=['⚗️','🧬','💊','📘','🧠']

export default function Analytics(){
 const navigate=useNavigate(),[data,setData]=useState<Overview|null>(null),[activities,setActivities]=useState<Activity[]>([]),[decks,setDecks]=useState<Deck[]>([]),[quizCounts,setQuizCounts]=useState<Record<string,number>>({}),[error,setError]=useState('')
 useEffect(()=>{Promise.all([api<Overview>('/analytics/overview'),api<{activities:Activity[]}>('/study-history?page=1&limit=100'),api<{stats:Deck[]}>('/flashcards/stats-by-topic'),api<{counts:Record<string,number>}>('/quizzes/counts-by-topic')]).then(([overview,history,deckStats,quizzes])=>{setData(overview);setActivities(history.activities);setDecks(deckStats.stats);setQuizCounts(quizzes.counts)}).catch(reason=>setError(messageFromError(reason)))},[])
 const breakdown=useMemo(()=>{const weekAgo=Date.now()-7*86400000,recent=activities.filter(a=>new Date(a.created_at).getTime()>=weekAgo);return [{label:'Cards reviewed',value:recent.filter(a=>a.activity_type==='flashcard_reviewed').length,color:'#6d5ef6'},{label:'Quizzes completed',value:recent.filter(a=>a.activity_type==='quiz_completed').length,color:'#5ab58e'},{label:'AI tutor conversations',value:recent.filter(a=>a.activity_type==='ai_chat').length,color:'#e8845a'},{label:'Notes added',value:recent.filter(a=>a.activity_type==='note_created').length,color:'#8e8982'}]},[activities])
 if(error)return <State text={error}/>;if(!data)return <State text="Loading analytics…"/>
 const max=Math.max(1,...data.activityTrend.map(x=>x.count)),avg=data.mastery.averageMastery==null?null:Math.round(data.mastery.averageMastery*100),breakMax=Math.max(1,...breakdown.map(x=>x.value))
 return <main className="analytics-page"><header><h1>Analytics</h1><p>Your progress across all topics, week by week.</p></header>
  <section className="metric-grid"><Metric icon="⏱️" value={data.activitiesThisWeek} label="Activities this week" note={`${data.totalActivities} all time`} color="#6d5ef6"/><Metric icon="🔥" value={data.currentStreak} label="Day streak" note={data.currentStreak===data.longestStreak&&data.currentStreak>0?'Personal best!':`Best: ${data.longestStreak} days`} color="#e8845a"/><Metric icon="⚡" value={data.totalXp.toLocaleString()} label="Total XP" note={data.overallLevelName} color="#5ab58e"/><Metric icon="📊" value={avg==null?'—':`${avg}%`} label="Avg. mastery" note={`${data.mastery.totalConcepts} concepts tracked`} color="#8e8982"/></section>
  <section className="chart-grid"><article className="panel activity-chart"><h2>7-day activity</h2><p>Recorded study actions</p><div className="bars">{data.activityTrend.map((item,index)=><div className="bar-column" key={item.date}><span>{item.count}</span><i className={index===data.activityTrend.length-2?'highlight':''} style={{height:`${Math.max(5,item.count/max*155)}px`}}/><small>{new Date(item.date+'T00:00:00').toLocaleDateString(undefined,{weekday:'short'})}</small></div>)}</div></article><article className="panel breakdown"><h2>Activity breakdown</h2><p>This week</p>{breakdown.map(item=><div className="break-row" key={item.label}><div><span>{item.label}</span><strong style={{color:item.color}}>{item.value}</strong></div><div><i style={{width:`${item.value/breakMax*100}%`,background:item.color}}/></div></div>)}</article></section>
  <section className="panel topics-panel"><h2>Per-topic breakdown</h2><div className="table-scroll"><table><thead><tr><th>Topic</th><th>Mastery</th><th>Total XP</th><th>Cards</th><th>Quizzes</th><th>Level</th></tr></thead><tbody>{data.topics.map((topic,index)=>{const color=COLORS[index%COLORS.length],mastery=topic.averageMastery==null?null:Math.round(topic.averageMastery*100),deck=decks.find(d=>d.topic_id===topic.topicId);return <tr key={topic.topicId} onClick={()=>navigate(`/app/topics/${topic.topicId}`)}><td><span className="topic-name"><i>{ICONS[index%ICONS.length]}</i><b>{topic.title}</b></span></td><td><span className="mastery-cell"><i><em style={{width:`${mastery??0}%`,background:color}}/></i><b style={{color}}>{mastery==null?'—':`${mastery}%`}</b></span></td><td>{topic.totalXp.toLocaleString()}</td><td>{deck?.total??0}</td><td>{quizCounts[String(topic.topicId)]??0}</td><td>{topic.levelName}</td></tr>})}</tbody></table></div>{!data.topics.length&&<p className="empty">Create topics and begin studying to see a breakdown.</p>}</section>
  <section className="panel weak-panel"><header><h2>Weakest concepts</h2><button onClick={()=>navigate('/app/coach')}>Open coach plan →</button></header>{data.weakestConcepts.map((concept,index)=>{const score=Math.round(concept.masteryScore*100),color=score<40?'#e8845a':'#6d5ef6';return <div className="weak-row" key={concept.conceptId}><span className="rank">{index+1}</span><div><span><b>{concept.conceptName}</b><strong style={{color}}>{score}%</strong></span><i><em style={{width:`${score}%`,background:color}}/></i><small>{concept.topicTitle}</small></div><button onClick={()=>navigate('/app/coach')}>Study</button></div>})}{!data.weakestConcepts.length&&<p className="empty">Complete quizzes and reviews to calculate concept mastery.</p>}</section>
  <style>{`
   .analytics-page{padding:45px 32px 90px;max-width:1240px;margin:0 auto;color:var(--color-text)}.analytics-page>header h1{font:700 39px/1.1 'Fraunces',Georgia,serif;margin:0 0 14px}.analytics-page>header p,.panel>p{color:var(--color-text-muted);margin:0}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin:42px 0 36px}.metric{min-height:170px;box-sizing:border-box;padding:26px;border:1px solid var(--color-border);border-radius:19px;background:var(--color-surface);display:flex;flex-direction:column}.metric>span{font-size:23px;margin-bottom:22px}.metric>b{font:700 34px 'Fraunces',serif;margin-bottom:8px}.metric label{color:var(--color-text-muted);font-size:14px}.metric small{margin-top:9px;font-weight:600}
   .panel{border:1px solid var(--color-border);border-radius:20px;background:var(--color-surface);overflow:hidden}.panel h2{font-size:17px;margin:0 0 11px}.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:26px}.activity-chart,.breakdown{padding:28px}.bars{height:205px;display:flex;align-items:flex-end;gap:12px;margin-top:18px}.bar-column{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:8px;color:var(--color-text-muted)}.bar-column span{font-size:12px}.bar-column i{display:block;width:100%;background:rgba(109,94,246,.15);border-radius:7px 7px 0 0}.bar-column i.highlight{background:#6d5ef6}.bar-column small{font-size:12px}.breakdown>p{margin-bottom:28px}.break-row{margin:20px 0}.break-row>div:first-child{display:flex;justify-content:space-between;margin-bottom:9px}.break-row>div:last-child{height:7px;background:var(--color-surface-2);border-radius:5px;overflow:hidden}.break-row i{display:block;height:100%;border-radius:5px}
   .topics-panel{margin-bottom:26px}.topics-panel>h2,.weak-panel>header{padding:23px 27px;margin:0;border-bottom:1px solid var(--color-border)}.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%;min-width:760px}th{text-transform:uppercase;text-align:left;font-size:12px;letter-spacing:.06em;color:var(--color-text-muted);background:var(--color-bg)}th,td{padding:18px 22px;border-bottom:1px solid var(--color-border)}tbody tr{cursor:pointer}tbody tr:hover{background:var(--color-surface-2)}.topic-name,.mastery-cell{display:flex;align-items:center;gap:12px}.topic-name i{font-style:normal;font-size:20px}.mastery-cell>i{width:72px;height:6px;background:var(--color-surface-2);border-radius:5px;overflow:hidden}.mastery-cell em{display:block;height:100%;border-radius:5px}.weak-panel>header{display:flex;justify-content:space-between;align-items:center}.weak-panel>header h2{margin:0}.weak-panel>header button,.weak-row>button{border:0;background:transparent;color:#6d5ef6;font-weight:600;cursor:pointer}.weak-row{display:grid;grid-template-columns:25px 1fr 65px;align-items:center;gap:10px;padding:16px 28px}.rank{color:var(--color-text-muted)}.weak-row>div>span{display:flex;justify-content:space-between;gap:12px}.weak-row>div>i{display:block;height:6px;background:var(--color-surface-2);border-radius:5px;overflow:hidden;margin:6px 0}.weak-row em{display:block;height:100%;border-radius:5px}.weak-row small{color:var(--color-text-muted)}.weak-row>button{padding:8px 12px;border-radius:9px;background:rgba(109,94,246,.12)}.empty{padding:25px;color:var(--color-text-muted)}
   @media(max-width:760px){.analytics-page{padding:38px 16px 85px}.analytics-page>header h1{font-size:38px}.analytics-page>header p{font-size:16px}.metric-grid{grid-template-columns:1fr 1fr;gap:15px;margin:40px 0}.metric{min-height:200px;padding:27px}.metric>b{font-size:32px}.chart-grid{grid-template-columns:1fr;gap:22px}.activity-chart,.breakdown{padding:28px}.bars{gap:9px}.topics-panel,.weak-panel{border-radius:19px}.topics-panel .table-scroll{overflow-x:auto}.weak-panel>header{padding:22px}.weak-row{padding:16px 20px;grid-template-columns:20px 1fr 58px}}
   @media(max-width:430px){.metric{min-height:185px;padding:22px}.metric>b{font-size:28px}.metric>span{margin-bottom:18px}.activity-chart,.breakdown{padding:22px}.bars{height:185px}.weak-panel>header button{font-size:12px}}
  `}</style>
 </main>
}

function Metric({icon,value,label,note,color}:{icon:string;value:string|number;label:string;note:string;color:string}){return <article className="metric"><span>{icon}</span><b>{value}</b><label>{label}</label><small style={{color}}>{note}</small></article>}
function State({text}:{text:string}){return <main style={{minHeight:'60vh',display:'grid',placeItems:'center',color:'var(--color-text-muted)'}}>{text}</main>}
