'use client'

import { useEffect, useMemo, useState } from 'react'
import { api, messageFromError } from '../lib/api'
import { useNavigate } from '../lib/navigation'

type Mistake={id:string;sourceType:string;sourceId:number;attemptId:number;topicId:number;topicTitle:string;activityTitle:string;concept:string;prompt:string;studentAnswer:string;correctAnswer:string;explanation:string;mistakeType:string|null;diagnosis:string|null;answeredAt:string}
const COLORS=['#6d5ef6','#e8845a','#5ab58e','#d5a928']

export default function Mistakes(){
 const navigate=useNavigate(),[items,setItems]=useState<Mistake[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[topic,setTopic]=useState('All'),[open,setOpen]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState('')
 useEffect(()=>{api<{mistakes:Mistake[]}>('/mistakes').then(result=>{setItems(result.mistakes);if(result.mistakes[0])setOpen(result.mistakes[0].id)}).catch(reason=>setError(messageFromError(reason))).finally(()=>setLoading(false))},[])
 const topics=useMemo(()=>['All',...new Set(items.map(item=>item.topicTitle))],[items]),shown=topic==='All'?items:items.filter(item=>item.topicTitle===topic),weekAgo=Date.now()-7*86400000,thisWeek=items.filter(item=>new Date(item.answeredAt).getTime()>=weekAgo).length,diagnosed=items.filter(item=>item.diagnosis||item.mistakeType).length
 const createFlashcard=async(item:Mistake)=>{setBusy(item.id);setError('');try{await api(`/topics/${item.topicId}/flashcards`,{method:'POST',body:JSON.stringify({question:item.prompt,answer:item.correctAnswer,explanation:item.explanation||item.diagnosis||null})});setMessage('Flashcard created from this mistake.')}catch(reason){setError(messageFromError(reason))}finally{setBusy(null)}}
 if(loading)return <State text="Loading mistakes…"/> 
 return <main className="mistakes-page"><header><h1>Mistake notebook</h1><p>Turn every wrong answer into understanding.</p></header>
  <section className="mistake-stats"><Stat icon="📖" value={items.length} label="Total mistakes"/><Stat icon="🗓️" value={thisWeek} label="This week"/><Stat icon="✅" value={diagnosed} label="Diagnosed"/></section>
  {(error||message)&&<div className={`mistake-notice ${error?'error':''}`}>{error||message}</div>}
  <nav className="topic-filters">{topics.map(value=><button className={topic===value?'active':''} key={value} onClick={()=>setTopic(value)}>{value}</button>)}</nav>
  <section className="mistake-list">{shown.map((item,index)=>{const expanded=open===item.id,color=COLORS[topics.indexOf(item.topicTitle)-1>=0?(topics.indexOf(item.topicTitle)-1)%COLORS.length:index%COLORS.length];return <article className={`mistake-card ${expanded?'expanded':''}`} key={item.id} style={{'--mistake-color':color} as React.CSSProperties}>
   <button className="mistake-summary" onClick={()=>setOpen(expanded?null:item.id)} aria-expanded={expanded}><i/><div><span className="badges"><b>{item.topicTitle}</b><em>{item.concept||'General'}</em></span><strong>{item.prompt}</strong><small>{relativeTime(item.answeredAt)}</small></div><span>{expanded?'▲':'▼'}</span></button>
   {expanded&&<div className="mistake-details"><div className="answer-grid"><div className="wrong"><b>Your answer</b><span>{item.studentAnswer}</span></div><div className="correct"><b>Correct answer</b><span>{item.correctAnswer}</span></div></div><div className="explanation"><b>Why you got this wrong</b><p>{item.diagnosis||item.explanation||'Review the correct answer and compare it with your response.'}</p><small>📄 Source: {item.activityTitle}</small></div><div className="mistake-actions"><button className="tutor" onClick={()=>navigate('/app/ai-tutor')}>💬 Ask tutor</button><button onClick={()=>void createFlashcard(item)} disabled={busy===item.id}>🃏 {busy===item.id?'Creating…':'Make flashcard'}</button>{item.sourceType==='quiz'&&<button onClick={()=>navigate(`/app/quizzes/take?id=${item.sourceId}`)}>📝 Try quiz again</button>}</div></div>}
  </article>})}{!shown.length&&<div className="mistake-empty">{error?error:'No mistakes found. Complete a quiz or exam to populate this page.'}</div>}</section>
  <style>{`
   .mistakes-page{padding:38px 32px 90px;max-width:1120px;margin:0 auto;color:var(--color-text)}.mistakes-page>header h1{font:700 40px/1.1 'Fraunces',Georgia,serif;margin:0 0 15px}.mistakes-page>header p{font-size:17px;color:var(--color-text-muted);margin:0}.mistake-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:42px 0 32px}.mistake-stat{min-height:150px;box-sizing:border-box;padding:25px;border:1px solid var(--color-border);border-radius:19px;background:var(--color-surface);display:flex;flex-direction:column;justify-content:center}.mistake-stat>span{font-size:22px;margin-bottom:20px}.mistake-stat>b{font:700 34px 'Fraunces',serif;margin-bottom:9px}.mistake-stat>small{font-size:15px;color:var(--color-text-muted)}
   .topic-filters{display:flex;gap:11px;overflow-x:auto;scrollbar-width:none;margin-bottom:28px}.topic-filters::-webkit-scrollbar{display:none}.topic-filters button{flex:0 0 auto;padding:11px 20px;border:1px solid var(--color-border);border-radius:24px;background:var(--color-surface);color:var(--color-text-2);font-weight:600;cursor:pointer}.topic-filters button.active{background:#6d5ef6;border-color:#6d5ef6;color:white}.mistake-list{display:flex;flex-direction:column;gap:16px}.mistake-card{border:1px solid var(--color-border);border-radius:20px;background:var(--color-surface);overflow:hidden}.mistake-summary{width:100%;min-height:118px;box-sizing:border-box;padding:22px 27px;display:grid;grid-template-columns:5px 1fr 18px;align-items:start;gap:18px;border:0;background:transparent;color:var(--color-text);text-align:left;cursor:pointer}.mistake-summary>i{width:5px;height:50px;border-radius:4px;background:var(--mistake-color)}.mistake-summary>div{display:flex;flex-direction:column;gap:9px}.badges{display:flex;gap:9px;flex-wrap:wrap}.badges b,.badges em{padding:6px 13px;border-radius:18px;font-size:12px;font-style:normal}.badges b{color:var(--mistake-color);background:color-mix(in srgb,var(--mistake-color) 11%,transparent)}.badges em{color:var(--color-text-muted);background:var(--color-surface-2)}.mistake-summary strong{font-size:15px;line-height:1.45}.mistake-summary small{color:var(--color-text-muted)}.mistake-summary>span:last-child{color:var(--color-text-muted);font-size:10px;margin-top:7px}
   .mistake-details{padding:27px;border-top:1px solid var(--color-border)}.answer-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.answer-grid>div{padding:19px;border-radius:15px;display:flex;flex-direction:column;gap:13px}.answer-grid b{font-size:13px}.answer-grid span{font-size:16px}.wrong{background:rgba(232,105,72,.13)}.wrong b{color:#d75d3c}.correct{background:rgba(90,181,142,.15)}.correct b{color:#398665}.explanation{margin-top:22px;padding:21px;border-radius:15px;background:var(--color-bg)}.explanation>b{color:#6d5ef6;font-size:13px}.explanation p{font-size:15px;line-height:1.65;margin:15px 0}.explanation small{color:var(--color-text-muted)}.mistake-actions{display:flex;gap:10px;margin-top:21px;flex-wrap:wrap}.mistake-actions button{padding:11px 16px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-bg);color:var(--color-text);font-weight:600;cursor:pointer}.mistake-actions .tutor{background:rgba(109,94,246,.12);border-color:transparent;color:#6d5ef6}.mistake-notice{margin:0 0 18px;padding:12px 15px;border-radius:10px;background:rgba(90,181,142,.13);color:#398665}.mistake-notice.error{background:rgba(232,105,72,.13);color:#d75d3c}.mistake-empty{padding:45px;text-align:center;border:1px dashed var(--color-border);border-radius:18px;color:var(--color-text-muted)}
   @media(max-width:650px){.mistakes-page{padding:22px 14px 85px}.mistakes-page>header{display:none}.mistake-stats{gap:13px;margin:0 0 35px}.mistake-stat{min-height:180px;padding:25px 20px}.mistake-stat>b{font-size:31px}.topic-filters{margin-right:-14px}.mistake-summary{padding:23px 20px;grid-template-columns:5px 1fr 15px}.mistake-summary strong{font-size:15px}.mistake-details{padding:30px}.answer-grid{grid-template-columns:1fr 1fr;gap:14px}.answer-grid>div{padding:17px}.explanation p{font-size:16px;line-height:1.8}.mistake-actions{flex-wrap:nowrap;overflow-x:auto}.mistake-actions button{flex:0 0 auto}}
   @media(max-width:430px){.mistake-stat{min-height:160px;padding:18px 14px}.mistake-stat>small{font-size:13px}.answer-grid{grid-template-columns:1fr}.mistake-details{padding:22px}}
  `}</style>
 </main>
}

function Stat({icon,value,label}:{icon:string;value:number;label:string}){return <article className="mistake-stat"><span>{icon}</span><b>{value}</b><small>{label}</small></article>}
function State({text}:{text:string}){return <main style={{minHeight:'60vh',display:'grid',placeItems:'center',color:'var(--color-text-muted)'}}>{text}</main>}
function relativeTime(value:string){const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<3600)return `${Math.floor(seconds/60)||1} minutes ago`;if(seconds<86400)return `${Math.floor(seconds/3600)} hours ago`;const days=Math.floor(seconds/86400);return days===1?'Yesterday':`${days} days ago`}
