'use client'

import { FormEvent, useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { api, downloadFile, messageFromError, uploadWithProgress } from '../lib/api'
import { useAuth } from '../contexts/AuthContext'
import { useTheme } from '../contexts/ThemeContext'
import ProfileAvatar from '../components/ProfileAvatar'

type Section = 'profile'|'notifications'|'appearance'|'learning'|'security'|'data'
type Session={id:string;device:string;ipAddress:string|null;createdAt:string;lastSeenAt:string|null;isCurrent:boolean}
type Learning={weights:Record<string,number>;dominantAxes:string[];eventCount:number;overridden:boolean;rationale:string}
type Usage={used:number;limit:number;remaining:number;softLimitHit:boolean}
type Plan={label:string}
type Reminder={emailEnabled:boolean;hourLocal:number;timezone:string;minimumDueCards:number}

const NAV:[Section,string][]=[['profile','Profile'],['notifications','Notifications'],['appearance','Appearance'],['learning','Learning style'],['security','Security & sessions'],['data','Data & export']]

export default function Settings(){
 const router=useRouter(),{user,refresh,logout}=useAuth(),{isDark,toggle}=useTheme(),fileRef=useRef<HTMLInputElement>(null)
 const [section,setSection]=useState<Section>('profile'),[name,setName]=useState(user?.name??''),[email,setEmail]=useState(user?.email??'')
 const [sessions,setSessions]=useState<Session[]>([]),[learning,setLearning]=useState<Learning|null>(null),[usage,setUsage]=useState<Usage|null>(null),[plan,setPlan]=useState<Plan|null>(null)
 const [reminder,setReminder]=useState<Reminder>({emailEnabled:false,hourLocal:20,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,minimumDueCards:1})
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')

 const load=async()=>{try{const [s,l,u,p,r]=await Promise.all([api<{sessions:Session[]}>('/users/me/sessions'),api<Learning>('/learning-style'),api<Usage>('/usage/me'),api<Plan>('/plans/me'),api<Reminder>('/reminders/preferences')]);setSessions(s.sessions);setLearning(l);setUsage(u);setPlan(p);setReminder(r)}catch(reason){setError(messageFromError(reason))}}
 useEffect(()=>{void load()},[])
 const success=(text:string)=>{setMessage(text);setError('');setTimeout(()=>setMessage(''),3000)}
 const fail=(reason:unknown)=>{setError(messageFromError(reason));setMessage('')}
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();try{await api('/auth/me',{method:'PATCH',body:JSON.stringify({name,email})});await refresh();success('Profile saved.')}catch(reason){fail(reason)}}
 const uploadPhoto=async(file?:File)=>{if(!file)return;const data=new FormData();data.append('image',file);try{await uploadWithProgress('/users/me/profile-image',data);await refresh();success('Profile photo updated.')}catch(reason){fail(reason)}}
 const saveReminder=async(next:Reminder)=>{setReminder(next);try{setReminder(await api('/reminders/preferences',{method:'PUT',body:JSON.stringify(next)}));success('Reminder preferences saved.')}catch(reason){fail(reason)}}
 const updatePassword=async(e:FormEvent)=>{e.preventDefault();if(newPassword!==confirmPassword){setError('New passwords do not match.');return}try{await api('/users/me/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword('');setNewPassword('');setConfirmPassword('');success('Password updated.')}catch(reason){fail(reason)}}
 const revoke=async(id:string)=>{try{await api(`/users/me/sessions/${id}`,{method:'DELETE'});await load()}catch(reason){fail(reason)}}
 const doLogout=async()=>{await logout();router.replace('/login')}
 const percent=usage?Math.min(100,Math.round(usage.used/Math.max(1,usage.limit)*100)):0

 return <main className="settings-page"><header><h1>Settings</h1><p>Manage your account, notifications, and preferences.</p></header>
  <section className="usage-banner"><div><strong>{plan?.label??'Current'} plan — {usage?.used??0} of {usage?.limit??0} AI requests used this month</strong><div className="usage-track"><i style={{width:`${percent}%`}}/></div><span>{percent}% used · {usage?.remaining??0} requests remaining</span></div><button onClick={()=>router.push('/app/billing')}>View plan</button></section>
  {(message||error)&&<div className={`notice ${error?'error':''}`}>{error||message}</div>}
  <div className="settings-layout"><nav className="settings-nav">{NAV.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}<hr/><button className="logout-nav" onClick={doLogout}>Log out</button></nav>
   <section className="settings-panel">
    {section==='profile'&&<form onSubmit={saveProfile}><h2>Profile</h2><div className="photo-row"><ProfileAvatar user={user} size={86}/><div><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" onClick={e=>{e.currentTarget.value=''}} onChange={e=>void uploadPhoto(e.target.files?.[0])}/><button type="button" className="soft-button" onClick={()=>fileRef.current?.click()}>Upload photo</button><span>JPG, PNG or WEBP up to 5MB</span></div></div><Field label="Full name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email address"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><button className="primary-button">Save changes</button></form>}
    {section==='notifications'&&<div><h2>Notifications</h2><div className="setting-row"><div><strong>Study reminders</strong><span>Daily nudge when cards are due</span></div><Toggle active={reminder.emailEnabled} onClick={()=>void saveReminder({...reminder,emailEnabled:!reminder.emailEnabled})}/></div><Field label="Reminder time"><input type="time" value={`${String(reminder.hourLocal).padStart(2,'0')}:00`} onChange={e=>void saveReminder({...reminder,hourLocal:Number(e.target.value.split(':')[0])})}/></Field><Field label="Minimum cards due"><input type="number" min={1} max={500} value={reminder.minimumDueCards} onChange={e=>setReminder({...reminder,minimumDueCards:Number(e.target.value)})} onBlur={()=>void saveReminder(reminder)}/></Field></div>}
    {section==='appearance'&&<div><h2>Appearance</h2><div className="setting-row appearance-row"><div><strong>{isDark?'Dark':'Light'} mode</strong><span>Choose the theme that is easier on your eyes</span></div><Toggle active={isDark} onClick={toggle}/></div><div className="theme-grid"><button className={!isDark?'selected':''} onClick={()=>isDark&&toggle()}><b>☀️</b><strong>Light</strong>{!isDark&&<span>Active</span>}</button><button className={isDark?'selected':''} onClick={()=>!isDark&&toggle()}><b>🌙</b><strong>Dark</strong>{isDark&&<span>Active</span>}</button></div></div>}
    {section==='learning'&&<div><h2>Learning style</h2><p className="description">{learning?.rationale||'Your learning preferences are calculated from real study activity.'}</p><div className="weights">{learning&&Object.entries(learning.weights).map(([key,value])=><div key={key}><span>{key}</span><div><i style={{width:`${Math.round(value*100)}%`}}/></div><b>{Math.round(value*100)}%</b></div>)}</div><button className="soft-button" onClick={async()=>{try{setLearning(await api('/learning-style/reset',{method:'POST'}));success('Learning style reset to automatic.')}catch(reason){fail(reason)}}}>Reset to automatic</button></div>}
    {section==='security'&&<div><h2>Security &amp; sessions</h2><h3>Active sessions</h3><div className="sessions">{sessions.map(session=><div key={session.id}><span><strong>{session.device}</strong><small>{session.ipAddress||'Unknown location'} · {session.lastSeenAt?new Date(session.lastSeenAt).toLocaleString():'Active now'}</small></span>{session.isCurrent?<em>This device</em>:<button onClick={()=>void revoke(session.id)}>Revoke</button>}</div>)}</div><form className="password-form" onSubmit={updatePassword}><h3>Change password</h3><Field label="Current password"><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></Field><Field label="New password"><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Field label="Confirm new password"><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></Field><button className="primary-button" disabled={!currentPassword||newPassword.length<8}>Update password</button></form></div>}
    {section==='data'&&<div><h2>Data &amp; export</h2><div className="data-card"><span>📦</span><div><strong>Export account data</strong><p>Download your topics, notes, study history, and account information.</p></div><button className="soft-button" onClick={()=>void downloadFile('/users/me/export','studia-account-data.json')}>Download export</button></div><div className="data-card logout-card"><span>↪</span><div><strong>Log out of Studia</strong><p>End your current session on this device.</p></div><button className="danger-button" onClick={doLogout}>Log out</button></div></div>}
   </section>
  </div>
  <style>{`
   .settings-page{padding:38px 32px 80px;max-width:1180px;margin:0 auto;color:var(--color-text)}.settings-page>header h1{font:700 40px/1.1 'Fraunces',Georgia,serif;margin:0 0 14px}.settings-page>header p{font-size:17px;color:var(--color-text-muted);margin:0}.usage-banner{margin:42px 0 35px;padding:25px 28px;border-radius:21px;background:rgba(109,94,246,.1);display:flex;align-items:center;justify-content:space-between;gap:25px}.usage-banner>div{flex:1}.usage-banner strong{color:#6d5ef6;font-size:15px}.usage-banner span{display:block;color:var(--color-text-2);font-size:13px;margin-top:8px}.usage-track{width:300px;max-width:100%;height:6px;border-radius:5px;background:var(--color-surface);margin-top:9px}.usage-track i{display:block;height:100%;border-radius:5px;background:#e8845a}.usage-banner button,.primary-button{padding:14px 25px;border:0;border-radius:12px;background:#6d5ef6;color:#fff;font-weight:700;font-size:15px;cursor:pointer}.notice{padding:11px 15px;margin:-20px 0 20px;border-radius:10px;background:rgba(90,181,142,.12);color:#388665}.notice.error{background:rgba(232,132,90,.12);color:#d46d43}
   .settings-layout{display:grid;grid-template-columns:260px 1fr;gap:35px;align-items:start}.settings-nav,.settings-panel{border:1px solid var(--color-border);border-radius:21px;background:var(--color-surface)}.settings-nav{padding:12px;display:flex;flex-direction:column}.settings-nav button{padding:15px 18px;text-align:left;border:0;border-radius:11px;background:transparent;color:var(--color-text);font:500 16px 'Outfit',sans-serif;cursor:pointer}.settings-nav button.active{background:rgba(109,94,246,.13);color:#6d5ef6;font-weight:700}.settings-nav hr{width:100%;border:0;border-top:1px solid var(--color-border);margin:8px 0}.settings-nav .logout-nav{color:#d05a3e}.settings-panel{min-height:370px;padding:30px}.settings-panel h2{font:700 27px 'Fraunces',serif;margin:0 0 30px}.settings-panel h3{margin:28px 0 18px}.description{color:var(--color-text-muted);line-height:1.6}
   .photo-row{display:flex;align-items:center;gap:20px;margin-bottom:30px}.avatar{width:86px;height:86px;border-radius:50%;display:grid;place-items:center;background:#ad915c;color:white;font-size:30px;font-weight:700}.photo-row>div:last-child{display:flex;flex-direction:column;align-items:flex-start;gap:8px}.photo-row span{font-size:13px;color:var(--color-text-muted)}.soft-button{padding:10px 16px;border:0;border-radius:10px;background:rgba(109,94,246,.13);color:#6d5ef6;font-weight:700;cursor:pointer}.field{display:block;margin:18px 0}.field>span{display:block;font-size:13px;font-weight:700;color:var(--color-text-2);margin-bottom:8px}.field input{width:100%;box-sizing:border-box;padding:14px 16px;border:1px solid var(--color-border);border-radius:11px;background:var(--color-bg);color:var(--color-text);font:500 15px 'Outfit',sans-serif}.primary-button{margin-top:8px}.primary-button:disabled{opacity:.5}
   .setting-row{display:flex;align-items:center;justify-content:space-between;padding:27px 0;border-bottom:1px solid var(--color-border)}.setting-row strong,.setting-row span{display:block}.setting-row span{color:var(--color-text-muted);margin-top:7px}.switch{width:65px;height:37px;border:0;border-radius:24px;background:#d3d0cc;padding:4px;cursor:pointer}.switch i{display:block;width:29px;height:29px;border-radius:50%;background:#fff;transition:transform .2s}.switch.on{background:#6d5ef6}.switch.on i{transform:translateX(28px)}.appearance-row{border:1px solid var(--color-border);border-radius:16px;padding:22px;margin-bottom:18px}.theme-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.theme-grid button{height:170px;border:2px solid var(--color-border);border-radius:16px;background:var(--color-bg);color:var(--color-text);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;cursor:pointer}.theme-grid button.selected{border-color:#6d5ef6;background:rgba(109,94,246,.1);color:#6d5ef6}.theme-grid b{font-size:30px}.theme-grid span{background:var(--color-surface);border-radius:15px;padding:4px 10px;font-size:12px}
   .weights{margin:25px 0}.weights>div{display:grid;grid-template-columns:110px 1fr 45px;align-items:center;gap:12px;margin:14px 0;text-transform:capitalize}.weights>div>div{height:8px;border-radius:6px;background:var(--color-surface-2)}.weights i{display:block;height:100%;border-radius:6px;background:#6d5ef6}.sessions>div{display:flex;align-items:center;justify-content:space-between;padding:17px 0;border-bottom:1px solid var(--color-border)}.sessions strong,.sessions small{display:block}.sessions small{color:var(--color-text-muted);margin-top:6px}.sessions em{font-style:normal;color:#4ca17b;background:rgba(90,181,142,.14);padding:7px 13px;border-radius:17px}.sessions button,.danger-button{padding:9px 15px;border:1px solid #df6948;border-radius:9px;background:transparent;color:#df6948;cursor:pointer}.password-form{margin-top:38px}.data-card{display:flex;align-items:center;gap:18px;padding:22px;border:1px solid var(--color-border);border-radius:15px;margin-bottom:14px}.data-card>span{font-size:28px}.data-card>div{flex:1}.data-card strong{font-size:16px}.data-card p{margin:6px 0 0;color:var(--color-text-muted);font-size:13px}.logout-card{border-color:rgba(208,90,62,.3)}
   @media(max-width:760px){.settings-page{padding:25px 15px 80px}.settings-page>header h1{font-size:34px}.usage-banner{margin:28px 0;align-items:flex-start;flex-direction:column}.settings-layout{grid-template-columns:1fr;gap:16px}.settings-nav{display:grid;grid-template-columns:repeat(2,1fr)}.settings-nav hr{display:none}.settings-panel{padding:22px}.theme-grid{grid-template-columns:1fr}.data-card{align-items:flex-start;flex-wrap:wrap}.data-card button{margin-left:45px}}
  `}</style>
 </main>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Toggle({active,onClick}:{active:boolean;onClick:()=>void}){return <button type="button" role="switch" aria-checked={active} className={`switch ${active?'on':''}`} onClick={onClick}><i/></button>}
