'use client'

import { useEffect, useMemo, useState } from 'react'
import { api, downloadFile, messageFromError, type Pagination } from '../lib/api'

type Activity={id:number;topic_id:number|null;topic_title:string|null;activity_type:string;description:string;created_at:string}
type Stats={total_activities?:number;activities_this_week?:number;ai_interactions?:number;topics_studied?:number;totalActivities?:number;activitiesThisWeek?:number;aiInteractions?:number;topicsStudied?:number}
type Filter='all'|'flashcards'|'quizzes'|'tutor'|'notes'
const FILTERS:[Filter,string][]=[['all','All'],['flashcards','Flashcards'],['quizzes','Quizzes'],['tutor','Tutor'],['notes','Notes']]
const TYPE_FOR:Record<Exclude<Filter,'all'>,string>={flashcards:'flashcard_reviewed',quizzes:'quiz_completed',tutor:'ai_chat',notes:'note_created'}
const ICONS:Record<string,string>={flashcard_reviewed:'🃏',flashcard_created:'🃏',flashcards_generated:'✨',quiz_completed:'📝',quiz_generated:'📝',ai_chat:'💬',note_created:'📄',note_updated:'📄',topic_created:'📚',topic_updated:'📚',diagnosis_viewed:'🔍',knowledge_graph_viewed:'🕸️',mind_map_viewed:'🧠'}

export default function StudyHistory(){
 const [activities,setActivities]=useState<Activity[]>([]),[pagination,setPagination]=useState<Pagination|null>(null),[stats,setStats]=useState<Stats|null>(null),[page,setPage]=useState(1),[filter,setFilter]=useState<Filter>('all'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false)
 useEffect(()=>{setLoading(true);setError('');const type=filter==='all'?'':`&type=${TYPE_FOR[filter]}`;Promise.all([api<{activities:Activity[];pagination:Pagination}>(`/study-history?page=${page}&limit=20${type}`),api<{stats:Stats}>('/study-history/stats')]).then(([history,summary])=>{setActivities(history.activities);setPagination(history.pagination);setStats(summary.stats)}).catch(reason=>setError(messageFromError(reason))).finally(()=>setLoading(false))},[page,filter])
 const groups=useMemo(()=>{const result=new Map<string,Activity[]>();activities.forEach(activity=>{const day=new Date(activity.created_at).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}).toUpperCase();result.set(day,[...(result.get(day)||[]),activity])});return [...result.entries()]},[activities])
 const total=stats?.total_activities??stats?.totalActivities??0,week=stats?.activities_this_week??stats?.activitiesThisWeek??0,ai=stats?.ai_interactions??stats?.aiInteractions??0
 const changeFilter=(next:Filter)=>{setFilter(next);setPage(1)}
 const exportPdf=async()=>{setExporting(true);try{await downloadFile('/reports/progress?format=pdf','studia-progress-report.pdf')}catch(reason){setError(messageFromError(reason))}finally{setExporting(false)}}
 return <main className="history-page"><header><h1>Study history</h1><p>A trustworthy record of everything you&apos;ve done.</p></header>
  <section className="history-stats"><Stat icon="📅" value={week} label="Activities (7 days)"/><Stat icon="💬" value={ai} label="AI interactions"/><Stat icon="📋" value={total} label="Total activities"/></section>
  <div className="history-toolbar"><nav>{FILTERS.map(([id,label])=><button className={filter===id?'active':''} key={id} onClick={()=>changeFilter(id)}>{label}</button>)}</nav><button className="export-button" disabled={exporting} onClick={()=>void exportPdf()}>{exporting?'Exporting…':'Export PDF'}</button></div>
  {error&&<div className="history-error">{error}</div>}
  {loading?<State text="Loading history…"/>:<section className="history-groups">{groups.map(([date,entries])=><div className="day-group" key={date}><h2>{date}</h2><div className="day-card">{entries.map(activity=><article key={activity.id}><div className="activity-icon">{ICONS[activity.activity_type]||'•'}</div><div className="activity-copy"><strong>{activity.description}</strong><span>{activity.topic_title&&<b>{activity.topic_title}</b>}<i>·</i>{new Date(activity.created_at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</span></div><small>{humanType(activity.activity_type)}</small></article>)}</div></div>)}{!groups.length&&<div className="history-empty">No activities found for this filter.</div>}</section>}
  {pagination&&pagination.totalPages>1&&<nav className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Previous</button><span>Page {page} of {pagination.totalPages}</span><button disabled={page===pagination.totalPages} onClick={()=>setPage(value=>value+1)}>Next →</button></nav>}
  <style>{`
   .history-page{padding:44px 32px 90px;max-width:1060px;margin:0 auto;color:var(--color-text)}.history-page>header h1{font:700 40px/1.1 'Fraunces',Georgia,serif;margin:0 0 15px}.history-page>header p{font-size:17px;color:var(--color-text-muted);margin:0}.history-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:42px 0 34px}.history-stat{min-height:150px;box-sizing:border-box;padding:25px;border:1px solid var(--color-border);border-radius:19px;background:var(--color-surface);display:flex;flex-direction:column;justify-content:center}.history-stat>span{font-size:22px;margin-bottom:20px}.history-stat>b{font:700 32px 'Fraunces',serif;margin-bottom:9px}.history-stat>small{font-size:15px;color:var(--color-text-muted)}
   .history-toolbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:32px}.history-toolbar nav{display:flex;gap:10px;flex-wrap:wrap}.history-toolbar button,.pagination button{padding:11px 20px;border:1px solid var(--color-border);border-radius:24px;background:var(--color-surface);color:var(--color-text-2);font:600 14px 'Outfit',sans-serif;cursor:pointer}.history-toolbar nav button.active{background:#6d5ef6;color:#fff;border-color:#6d5ef6}.export-button{white-space:nowrap}.day-group{margin-bottom:31px}.day-group>h2{font-size:13px;color:var(--color-text-muted);letter-spacing:.04em;margin:0 0 14px 3px}.day-card{border:1px solid var(--color-border);border-radius:19px;background:var(--color-surface);overflow:hidden}.day-card article{min-height:90px;box-sizing:border-box;padding:18px 25px;display:flex;align-items:center;gap:20px;border-bottom:1px solid var(--color-border)}.day-card article:last-child{border-bottom:0}.activity-icon{width:48px;height:48px;border-radius:12px;background:rgba(109,94,246,.09);display:grid;place-items:center;font-size:20px;flex:0 0 auto}.activity-copy{flex:1;min-width:0}.activity-copy strong{display:block;font-size:15px;margin-bottom:8px}.activity-copy span{display:flex;align-items:center;gap:10px;color:var(--color-text-muted);font-size:13px}.activity-copy b{color:#6d5ef6}.activity-copy i{font-style:normal}.day-card article>small{color:#5ab58e;text-transform:capitalize;font-weight:600}.history-error{padding:12px 15px;margin-bottom:20px;border-radius:10px;background:rgba(232,105,72,.13);color:#d75d3c}.history-empty{padding:50px;text-align:center;border:1px dashed var(--color-border);border-radius:18px;color:var(--color-text-muted)}.pagination{display:flex;justify-content:center;align-items:center;gap:16px}.pagination button:disabled{opacity:.45;cursor:default}.pagination span{font-size:13px;color:var(--color-text-muted)}
   @media(max-width:650px){.history-page{padding:44px 17px 85px}.history-page>header h1{font-size:39px}.history-page>header p{font-size:16px;line-height:1.55}.history-stats{gap:13px;margin:42px 0 35px}.history-stat{min-height:220px;padding:24px 20px;justify-content:flex-start}.history-stat>span{margin:8px 0 25px}.history-stat>b{font-size:30px;line-height:1.45}.history-stat>small{line-height:1.5}.history-toolbar{align-items:flex-start}.history-toolbar nav{gap:10px}.history-toolbar .export-button{align-self:flex-end}.day-card article{padding:22px 25px;align-items:flex-start}.activity-copy strong{font-size:15px;line-height:1.45}.activity-copy span{flex-wrap:wrap}.day-card article>small{align-self:center}.activity-icon{margin-top:4px}}
   @media(max-width:480px){.history-toolbar{display:block}.history-toolbar nav{display:flex}.history-toolbar .export-button{float:right;margin-top:10px}.history-groups{clear:both;padding-top:30px}.day-card article{display:grid;grid-template-columns:52px 1fr}.day-card article>small{grid-column:2}.history-stat{min-height:205px;padding:18px 13px}.history-stat>b{font-size:26px}.history-stat>small{font-size:13px}}
  `}</style>
 </main>}

function Stat({icon,value,label}:{icon:string;value:number;label:string}){return <article className="history-stat"><span>{icon}</span><b>{value.toLocaleString()}</b><small>{label}</small></article>}
function State({text}:{text:string}){return <div style={{minHeight:220,display:'grid',placeItems:'center',color:'var(--color-text-muted)'}}>{text}</div>}
function humanType(type:string){return type.replaceAll('_',' ')}
